ci(tests): Add E2E test that self-references this action (#155)
* ci(tests): Add E2E test that self-references this action

* ci(lint): Upgrade to Go 1.20

* ci(test): Pass ref_name into callable workflow

* ci: Try quoting action ref

* ci: Try using path reference to action.yml

* ci: Try using literal path reference to action.yml

* ci: Try using .. path reference to action.yml

* ci(e2e): Move continue-on-error to job level

* ci(e2e): Use step outcome, not conclusion

* ci: Remove ref_name input

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -40,3 +40,44 @@ jobs:
     - uses: actions/checkout@v3
     - name: Build and test the Docker image
       run: test/test.sh ${{ matrix.clang-format-version }}
+  e2e:
+    name: E2E ${{ inputs.runner-os }}-clang-format-${{ matrix.clang-format-version }}-${{ matrix.path['check'] }}
+    runs-on: ${{ inputs.runner-os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        clang-format-version:
+          - 3
+          - 4
+          - 5
+          - 6
+          - 7
+          - 8
+          - 9
+          - 10
+          - 11
+          - 12
+          - 13
+          - 14
+          - 15
+          - 16
+        path:
+          - check: 'test/known_fail'
+            exclude: 'capi'
+            known_fail: true
+          - check: 'test/known_pass'
+            exclude: 'capi'
+            known_fail: false
+    steps:
+      - uses: actions/checkout@v3
+      - name: Run clang-format style check for C/C++ programs.
+        id: check
+        uses: ./../clang-format-action
+        continue-on-error: ${{ matrix.path['known_fail'] }}
+        with:
+          check-path: ${{ matrix.path['check'] }}
+          clang-format-version: ${{ matrix.clang-format-version }}
+          exclude-regex: ${{ matrix.path['exclude'] }}
+      - name: Incorrect success on known-fail test
+        if: ${{ steps.check.outcome == 'success' && matrix.path['known_fail'] }}
+        run: exit 1
